# Generated by Django 5.1 on 2024-11-10 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome')),
                ('birthday', models.DateField(verbose_name='Data de nascimento')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="O número de telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de telefone')),
                ('objective', models.CharField(max_length=500, verbose_name='Objetivo')),
                ('frequency', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Escolha no Minimo 1 vez na semana'), django.core.validators.MaxValueValidator(6, 'O maximo é 6 vezes na semana')])),
                ('active', models.BooleanField(verbose_name='Ativo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
