# Generated by Django 5.1 on 2024-11-10 17:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaches', '0001_initial'),
        ('exercises', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='group')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Series')),
                ('repetitions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Adicione no maximo uma repetição'), django.core.validators.MaxValueValidator(50, 'É permitido no maximo 50 repetições')], verbose_name='Repetições')),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Tempo de descanso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coaches.coach', verbose_name='Treinador')),
                ('exercice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.exercice', verbose_name='Exercicio')),
                ('group', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='training_sheet.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Aluno')),
            ],
        ),
    ]
