# Generated by Django 5.1 on 2024-11-10 17:55

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome')),
                ('birthday', models.DateField(verbose_name='Data de nascimento')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="O número de telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Número de Telefone')),
                ('specialty', models.CharField(blank=True, max_length=255, null=True, verbose_name='Especialidade')),
                ('entry', models.DateField(verbose_name='Dia da contratação')),
                ('start_job', models.TimeField(verbose_name='Horario de inicio de expediente')),
                ('ends_job', models.TimeField(verbose_name='Horario do fim do expediente')),
                ('working_days', multiselectfield.db.fields.MultiSelectField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=27)),
                ('status', models.CharField(choices=[('AT', 'Ativo'), ('IN', 'Inativo'), ('FE', 'Férias')], max_length=50)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
