# Generated by Django 5.1 on 2024-11-10 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muscle_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Musculação', 'Musculação'), ('Cardio', 'Cardio')], max_length=255)),
                ('difficulty_level', models.CharField(choices=[('Facíl', 'Facíl'), ('Intermediário', 'Intermediário'), ('Difícil', 'Difícil')], max_length=255)),
                ('equipment', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='exercices/')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('muscle_groups', models.ManyToManyField(related_name='MuscleGroups', to='muscle_groups.musclegroups')),
            ],
        ),
    ]
